const withDefaults = (item, sortOrder) => ({
  groupKey: "GHG",
  requiresFactor: true,
  evidenceRequired: true,
  sdgs: [],
  sortOrder,
  isActive: true,
  ...item,
});

export const SCOPE3_SUPPORT_MATRIX = [
  { category: 1, label: "Purchased goods and services", status: "supported", methodSupport: ["spend", "activity"], starterFactorCoverage: "starter_available", note: "Starter spend and activity factors are available in the baseline library." },
  { category: 2, label: "Capital goods", status: "supported", methodSupport: ["spend"], starterFactorCoverage: "starter_available", note: "Starter spend factor is available; sector-specific enrichment remains optional." },
  { category: 3, label: "Fuel- and energy-related activities", status: "supported", methodSupport: ["activity"], starterFactorCoverage: "starter_available", note: "Starter upstream fuel factor is available." },
  { category: 4, label: "Upstream transportation and distribution", status: "supported", methodSupport: ["activity"], starterFactorCoverage: "starter_available", note: "Starter freight factor is available; transport mode metadata improves match quality." },
  { category: 5, label: "Waste generated in operations", status: "supported", methodSupport: ["activity"], starterFactorCoverage: "starter_available", note: "Starter waste factor is available; treatment and region metadata improve specificity." },
  { category: 6, label: "Business travel", status: "supported", methodSupport: ["activity"], starterFactorCoverage: "starter_available", note: "Starter flight, rail, and hotel factors are available." },
  { category: 7, label: "Employee commuting", status: "supported", methodSupport: ["activity"], starterFactorCoverage: "starter_available", note: "Starter commuting factor is available; transport mode metadata improves specificity." },
  { category: 8, label: "Upstream leased assets", status: "partial", methodSupport: ["activity"], starterFactorCoverage: "starter_available", note: "Structured activity input and starter energy proxy factor are available. Treat results as screening-grade unless asset-specific energy intensity is documented." },
  { category: 9, label: "Downstream transportation and distribution", status: "supported", methodSupport: ["activity"], starterFactorCoverage: "starter_available", note: "Starter freight factor is available; transport mode metadata improves match quality." },
  { category: 10, label: "Processing of sold products", status: "partial", methodSupport: ["activity"], starterFactorCoverage: "starter_available", note: "Structured activity input and a proxy processing factor are available. Sector-specific process factors should replace the starter value before external assurance." },
  { category: 11, label: "Use of sold products", status: "partial", methodSupport: ["activity"], starterFactorCoverage: "starter_available", note: "Structured use-phase input is available with a starter electricity proxy. Confirm load profile, operating hours and geography before treating totals as committed." },
  { category: 12, label: "End-of-life treatment of sold products", status: "supported", methodSupport: ["activity"], starterFactorCoverage: "starter_available", note: "Starter end-of-life factor is available." },
  { category: 13, label: "Downstream leased assets", status: "partial", methodSupport: ["activity"], starterFactorCoverage: "starter_available", note: "Structured downstream leased energy input is available with a starter proxy factor. Treat as screening-grade until lease-specific consumption and tenant splits are validated." },
  { category: 14, label: "Franchises", status: "supported", methodSupport: ["spend"], starterFactorCoverage: "starter_available", note: "Starter spend factor is available." },
  { category: 15, label: "Investments", status: "supported", methodSupport: ["direct_tco2e"], starterFactorCoverage: "not_required", note: "Supported through direct tCO2e entry; no factor resolution is required." },
];

export const getScope3SupportEntry = (category) =>
  SCOPE3_SUPPORT_MATRIX.find((item) => Number(item.category) === Number(category)) || null;

export const buildScope3SupportWarnings = (categories = []) => {
  const warnings = [];
  for (const category of [...new Set(categories.map((item) => Number(item)).filter(Number.isInteger))]) {
    const entry = getScope3SupportEntry(category);
    if (!entry) {
      continue;
    }
    if (entry.status === "supported") {
      continue;
    }
    const prefix =
      entry.status === "not_enabled"
        ? "not enabled for automated pilot coverage"
        : "only partially supported";
    warnings.push(`Scope 3 category ${entry.category} (${entry.label}) is ${prefix}. ${entry.note}`);
  }
  return warnings;
};

export const GHG_ACTIVITY_BASELINE = [
  withDefaults(
    {
      scope: "scope1",
      key: "s1_stationary_natural_gas_mwh",
      name: "Stationary combustion · Natural gas",
      subGroup: "Combustion",
      method: "activity",
      unit: "MWh",
      defaultFactorKey: "ef_natural_gas_kgco2e_per_mwh",
      sdgs: [7, 12, 13],
      inputSchema: {
        fields: [
          { key: "asset_type", type: "text", required: false },
          { key: "lease_share_pct", type: "number", required: false },
          { key: "energy_source", type: "select", required: false, options: ["electricity", "mixed"] },
        ],
      },
    },
    10,
  ),
  withDefaults(
    {
      scope: "scope1",
      key: "s1_stationary_fuel_oil_liters",
      name: "Stationary combustion · Fuel oil",
      subGroup: "Combustion",
      method: "activity",
      unit: "liters",
      defaultFactorKey: "ef_s1_fuel_oil_kgco2e_per_liter",
      sdgs: [7, 12, 13],
      inputSchema: { fields: [] },
    },
    20,
  ),
  withDefaults(
    {
      scope: "scope1",
      key: "s1_stationary_lpg_liters",
      name: "Stationary combustion · LPG",
      subGroup: "Combustion",
      method: "activity",
      unit: "liters",
      defaultFactorKey: "ef_s1_lpg_kgco2e_per_liter",
      sdgs: [7, 12, 13],
      inputSchema: { fields: [] },
    },
    30,
  ),
  withDefaults(
    {
      scope: "scope1",
      key: "s1_stationary_coal_tons",
      name: "Stationary combustion · Coal",
      subGroup: "Combustion",
      method: "activity",
      unit: "tons",
      defaultFactorKey: "ef_s1_coal_kgco2e_per_ton",
      sdgs: [7, 12, 13],
      inputSchema: { fields: [] },
    },
    40,
  ),
  withDefaults(
    {
      scope: "scope1",
      key: "s1_stationary_biomass_tons",
      name: "Stationary combustion · Biomass",
      subGroup: "Combustion",
      method: "activity",
      unit: "tons",
      defaultFactorKey: "ef_s1_biomass_kgco2e_per_ton",
      sdgs: [7, 12, 13, 15],
      inputSchema: {
        fields: [{ key: "biogenic", type: "boolean", required: false, label: "Biogenic emissions reported separately" }],
      },
    },
    50,
  ),
  withDefaults(
    {
      scope: "scope1",
      key: "s1_mobile_diesel_liters",
      name: "Mobile combustion · Diesel",
      subGroup: "Mobile",
      method: "activity",
      unit: "liters",
      defaultFactorKey: "ef_diesel_kgco2e_per_liter",
      sdgs: [9, 12, 13],
      inputSchema: {
        fields: [
          {
            key: "transport_mode",
            type: "select",
            required: false,
            options: ["road", "rail", "sea", "air"],
          },
        ],
      },
    },
    60,
  ),
  withDefaults(
    {
      scope: "scope1",
      key: "s1_mobile_gasoline_liters",
      name: "Mobile combustion · Gasoline",
      subGroup: "Mobile",
      method: "activity",
      unit: "liters",
      defaultFactorKey: "ef_gasoline_kgco2e_per_liter",
      sdgs: [9, 12, 13],
      inputSchema: {
        fields: [
          {
            key: "transport_mode",
            type: "select",
            required: false,
            options: ["road", "rail", "sea", "air"],
          },
        ],
      },
    },
    70,
  ),
  withDefaults(
    {
      scope: "scope1",
      key: "s1_mobile_fleet_km",
      name: "Mobile combustion · Fleet distance",
      subGroup: "Mobile",
      method: "activity",
      unit: "km",
      defaultFactorKey: "ef_s1_fleet_kgco2e_per_km",
      sdgs: [9, 11, 13],
      inputSchema: {
        fields: [
          {
            key: "transport_mode",
            type: "select",
            required: true,
            options: ["road", "rail", "sea", "air"],
          },
        ],
      },
    },
    80,
  ),
  withDefaults(
    {
      scope: "scope1",
      key: "s1_mobile_maritime_fuel_tons",
      name: "Mobile combustion · Maritime fuel",
      subGroup: "Mobile",
      method: "activity",
      unit: "tons",
      defaultFactorKey: "ef_s1_maritime_fuel_kgco2e_per_ton",
      sdgs: [9, 13, 14],
      inputSchema: { fields: [{ key: "vessel_type", type: "text", required: false }] },
    },
    90,
  ),
  withDefaults(
    {
      scope: "scope1",
      key: "s1_mobile_aviation_fuel_tons",
      name: "Mobile combustion · Aviation fuel",
      subGroup: "Mobile",
      method: "activity",
      unit: "tons",
      defaultFactorKey: "ef_s1_aviation_fuel_kgco2e_per_ton",
      sdgs: [9, 13],
      inputSchema: { fields: [{ key: "fleet_controlled", type: "boolean", required: false }] },
    },
    100,
  ),
  withDefaults(
    {
      scope: "scope1",
      key: "s1_refrigerant_leakage_kg",
      name: "Fugitive emissions · Refrigerant leakage",
      subGroup: "Refrigerants",
      method: "activity",
      unit: "kg",
      defaultFactorKey: "ef_refrigerant_kgco2e_per_kg",
      sdgs: [12, 13],
      inputSchema: {
        fields: [
          {
            key: "refrigerant_type",
            type: "select",
            required: true,
            options: ["R134A", "R410A", "R32", "R22", "R407C", "R404A"],
          },
        ],
      },
    },
    110,
  ),
  withDefaults(
    {
      scope: "scope1",
      key: "s1_process_cement_clinker_tons",
      name: "Process emissions · Cement clinker",
      subGroup: "Process",
      method: "activity",
      unit: "tons",
      defaultFactorKey: "ef_s1_process_cement_clinker_kgco2e_per_ton",
      sdgs: [9, 12, 13],
      inputSchema: { fields: [] },
    },
    120,
  ),
  withDefaults(
    {
      scope: "scope1",
      key: "s1_process_lime_tons",
      name: "Process emissions · Lime",
      subGroup: "Process",
      method: "activity",
      unit: "tons",
      defaultFactorKey: "ef_s1_process_lime_kgco2e_per_ton",
      sdgs: [9, 12, 13],
      inputSchema: { fields: [] },
    },
    130,
  ),
  withDefaults(
    {
      scope: "scope1",
      key: "s1_process_ammonia_tons",
      name: "Process emissions · Ammonia",
      subGroup: "Process",
      method: "activity",
      unit: "tons",
      defaultFactorKey: "ef_s1_process_ammonia_kgco2e_per_ton",
      sdgs: [9, 12, 13],
      inputSchema: { fields: [] },
    },
    140,
  ),

  withDefaults(
    {
      scope: "scope2",
      key: "s2_purchased_electricity_location_kwh",
      name: "Purchased electricity (location-based)",
      subGroup: "Electricity",
      method: "activity",
      unit: "kWh",
      defaultFactorKey: "ef_scope2_location_kgco2e_per_kwh",
      sdgs: [7, 12, 13],
      inputSchema: { fields: [{ key: "market_instrument", type: "text", required: false }] },
    },
    200,
  ),
  withDefaults(
    {
      scope: "scope2",
      key: "s2_purchased_electricity_market_kwh",
      name: "Purchased electricity (market-based)",
      subGroup: "Electricity",
      method: "activity",
      unit: "kWh",
      defaultFactorKey: "ef_scope2_market_kgco2e_per_kwh",
      sdgs: [7, 12, 13],
      inputSchema: { fields: [{ key: "contract_type", type: "text", required: false }] },
    },
    210,
  ),
  withDefaults(
    {
      scope: "scope2",
      key: "s2_purchased_steam_mwh",
      name: "Purchased steam",
      subGroup: "Heat & Cooling",
      method: "activity",
      unit: "MWh",
      defaultFactorKey: "ef_s2_steam_kgco2e_per_mwh",
      sdgs: [7, 12, 13],
      inputSchema: { fields: [] },
    },
    220,
  ),
  withDefaults(
    {
      scope: "scope2",
      key: "s2_purchased_heat_mwh",
      name: "Purchased heat",
      subGroup: "Heat & Cooling",
      method: "activity",
      unit: "MWh",
      defaultFactorKey: "ef_s2_heat_kgco2e_per_mwh",
      sdgs: [7, 12, 13],
      inputSchema: { fields: [] },
    },
    230,
  ),
  withDefaults(
    {
      scope: "scope2",
      key: "s2_purchased_cooling_mwh",
      name: "Purchased cooling",
      subGroup: "Heat & Cooling",
      method: "activity",
      unit: "MWh",
      defaultFactorKey: "ef_s2_cooling_kgco2e_per_mwh",
      sdgs: [7, 12, 13],
      inputSchema: { fields: [] },
    },
    240,
  ),
  withDefaults(
    {
      scope: "scope2",
      key: "s2_renewable_certificates_kwh",
      name: "Renewable certificates (REC/GO)",
      subGroup: "Electricity",
      method: "activity",
      unit: "kWh",
      defaultFactorKey: "ef_s2_renewable_certificate_kgco2e_per_kwh",
      sdgs: [7, 12, 13],
      inputSchema: {
        fields: [
          { key: "certificate_type", type: "select", required: false, options: ["REC", "GO", "I-REC"] },
        ],
      },
    },
    250,
  ),

  withDefaults(
    {
      scope: "scope3",
      scope3Category: 1,
      key: "s3_cat1_purchased_goods_spend",
      name: "Purchased goods & services · Spend",
      subGroup: "Purchased goods",
      method: "spend",
      unit: "EUR",
      defaultFactorKey: "ef_s3_cat1_spend_kgco2e_per_eur",
      sdgs: [8, 9, 12, 13],
      inputSchema: {
        fields: [
          { key: "spend_category", type: "text", required: false },
          { key: "supplier_name", type: "text", required: false },
        ],
      },
    },
    300,
  ),
  withDefaults(
    {
      scope: "scope3",
      scope3Category: 1,
      key: "s3_cat1_paper_tons",
      name: "Purchased goods & services · Paper",
      subGroup: "Purchased goods",
      method: "activity",
      unit: "tons",
      defaultFactorKey: "ef_s3_cat1_paper_kgco2e_per_ton",
      sdgs: [12, 13, 15],
      inputSchema: { fields: [] },
    },
    310,
  ),
  withDefaults(
    {
      scope: "scope3",
      scope3Category: 1,
      key: "s3_cat1_packaging_tons",
      name: "Purchased goods & services · Packaging",
      subGroup: "Purchased goods",
      method: "activity",
      unit: "tons",
      defaultFactorKey: "ef_s3_cat1_packaging_kgco2e_per_ton",
      sdgs: [12, 13],
      inputSchema: { fields: [] },
    },
    320,
  ),
  withDefaults(
    {
      scope: "scope3",
      scope3Category: 2,
      key: "s3_cat2_capital_goods_spend",
      name: "Capital goods · Spend",
      subGroup: "Capital goods",
      method: "spend",
      unit: "EUR",
      defaultFactorKey: "ef_s3_cat2_capex_kgco2e_per_eur",
      sdgs: [9, 12, 13],
      inputSchema: { fields: [{ key: "asset_class", type: "text", required: false }] },
    },
    330,
  ),
  withDefaults(
    {
      scope: "scope3",
      scope3Category: 3,
      key: "s3_cat3_well_to_tank_fuels",
      name: "Fuel- and energy-related activities · Well-to-tank fuels",
      subGroup: "Fuel and energy",
      method: "activity",
      unit: "liters",
      defaultFactorKey: "ef_s3_cat3_wtt_fuel_kgco2e_per_liter",
      sdgs: [7, 12, 13],
      inputSchema: { fields: [{ key: "fuel_type", type: "text", required: false }] },
    },
    340,
  ),
  withDefaults(
    {
      scope: "scope3",
      scope3Category: 4,
      key: "s3_cat4_upstream_freight_ton_km",
      name: "Upstream transportation & distribution · Freight",
      subGroup: "Transport",
      method: "activity",
      unit: "ton_km",
      defaultFactorKey: "ef_s3_cat4_freight_kgco2e_per_ton_km",
      sdgs: [9, 11, 12, 13],
      inputSchema: {
        fields: [
          {
            key: "transport_mode",
            type: "select",
            required: true,
            options: ["road", "rail", "sea", "air"],
          },
        ],
      },
    },
    350,
  ),
  withDefaults(
    {
      scope: "scope3",
      scope3Category: 5,
      key: "s3_cat5_waste_tons",
      name: "Waste generated in operations",
      subGroup: "Waste",
      method: "activity",
      unit: "tons",
      defaultFactorKey: "ef_s3_cat5_waste_kgco2e_per_ton",
      sdgs: [12, 13],
      inputSchema: {
        fields: [
          {
            key: "treatment",
            type: "select",
            required: true,
            options: ["landfill", "incineration", "recycle", "compost"],
          },
          { key: "region", type: "text", required: false },
        ],
      },
    },
    360,
  ),
  withDefaults(
    {
      scope: "scope3",
      scope3Category: 6,
      key: "s3_cat6_flights_pax_km",
      name: "Business travel · Flights",
      subGroup: "Business travel",
      method: "activity",
      unit: "pax_km",
      defaultFactorKey: "ef_s3_cat6_flight_kgco2e_per_pax_km",
      sdgs: [8, 12, 13],
      inputSchema: {
        fields: [
          { key: "flight_class", type: "select", required: false, options: ["economy", "premium", "business", "first"] },
        ],
      },
    },
    370,
  ),
  withDefaults(
    {
      scope: "scope3",
      scope3Category: 6,
      key: "s3_cat6_rail_km",
      name: "Business travel · Rail",
      subGroup: "Business travel",
      method: "activity",
      unit: "km",
      defaultFactorKey: "ef_s3_cat6_rail_kgco2e_per_km",
      sdgs: [8, 9, 13],
      inputSchema: { fields: [] },
    },
    371,
  ),
  withDefaults(
    {
      scope: "scope3",
      scope3Category: 6,
      key: "s3_cat6_hotel_nights",
      name: "Business travel · Hotel nights",
      subGroup: "Business travel",
      method: "activity",
      unit: "nights",
      defaultFactorKey: "ef_s3_cat6_hotel_kgco2e_per_night",
      sdgs: [8, 12, 13],
      inputSchema: { fields: [{ key: "hotel_class", type: "text", required: false }] },
    },
    372,
  ),
  withDefaults(
    {
      scope: "scope3",
      scope3Category: 7,
      key: "s3_cat7_commuting_km",
      name: "Employee commuting · Distance",
      subGroup: "Employee commuting",
      method: "activity",
      unit: "km",
      defaultFactorKey: "ef_s3_cat7_commute_kgco2e_per_km",
      sdgs: [3, 8, 11, 13],
      inputSchema: {
        fields: [
          {
            key: "transport_mode",
            type: "select",
            required: true,
            options: ["car", "bus", "train", "metro", "bike", "walk"],
          },
          { key: "days", type: "number", required: false },
          { key: "remote_work_days", type: "number", required: false },
        ],
      },
    },
    380,
  ),
  withDefaults(
    {
      scope: "scope3",
      scope3Category: 8,
      key: "s3_cat8_upstream_leased_energy_kwh",
      name: "Upstream leased assets · Electricity",
      subGroup: "Leased assets",
      method: "activity",
      unit: "kWh",
      defaultFactorKey: "ef_s3_cat8_leased_energy_kgco2e_per_kwh",
      sdgs: [7, 12, 13],
      inputSchema: { fields: [] },
    },
    390,
  ),
  withDefaults(
    {
      scope: "scope3",
      scope3Category: 9,
      key: "s3_cat9_downstream_freight_ton_km",
      name: "Downstream transportation & distribution · Freight",
      subGroup: "Transport",
      method: "activity",
      unit: "ton_km",
      defaultFactorKey: "ef_s3_cat9_freight_kgco2e_per_ton_km",
      sdgs: [9, 11, 12, 13],
      inputSchema: {
        fields: [
          {
            key: "transport_mode",
            type: "select",
            required: true,
            options: ["road", "rail", "sea", "air"],
          },
        ],
      },
    },
    400,
  ),
  withDefaults(
    {
      scope: "scope3",
      scope3Category: 10,
      key: "s3_cat10_processing_activity",
      name: "Processing of sold products",
      subGroup: "Downstream",
      method: "activity",
      unit: "ton",
      defaultFactorKey: "ef_s3_cat10_processing_kgco2e_per_ton",
      sdgs: [9, 12, 13],
      inputSchema: {
        fields: [
          { key: "process_type", type: "text", required: true },
          { key: "processed_material", type: "text", required: false },
          { key: "proxy_basis", type: "select", required: false, options: ["starter_proxy", "supplier_specific"] },
        ],
      },
    },
    410,
  ),
  withDefaults(
    {
      scope: "scope3",
      scope3Category: 11,
      key: "s3_cat11_use_of_sold_products_kwh",
      name: "Use of sold products · Energy use",
      subGroup: "Downstream",
      method: "activity",
      unit: "kWh",
      defaultFactorKey: "ef_s3_cat11_use_phase_kgco2e_per_kwh",
      sdgs: [7, 12, 13],
      inputSchema: {
        fields: [
          { key: "lifetime_years", type: "number", required: false },
          { key: "products_sold", type: "number", required: false },
          { key: "annual_use_hours", type: "number", required: false },
          { key: "region", type: "text", required: false },
        ],
      },
    },
    420,
  ),
  withDefaults(
    {
      scope: "scope3",
      scope3Category: 12,
      key: "s3_cat12_end_of_life_tons",
      name: "End-of-life treatment of sold products",
      subGroup: "Downstream",
      method: "activity",
      unit: "tons",
      defaultFactorKey: "ef_s3_cat12_eol_kgco2e_per_ton",
      sdgs: [12, 13],
      inputSchema: {
        fields: [
          { key: "material", type: "text", required: false },
          { key: "disposal_route", type: "text", required: false },
        ],
      },
    },
    430,
  ),
  withDefaults(
    {
      scope: "scope3",
      scope3Category: 13,
      key: "s3_cat13_downstream_leased_assets_kwh",
      name: "Downstream leased assets · Energy",
      subGroup: "Downstream",
      method: "activity",
      unit: "kWh",
      defaultFactorKey: "ef_s3_cat13_leased_assets_kgco2e_per_kwh",
      sdgs: [7, 12, 13],
      inputSchema: {
        fields: [
          { key: "asset_type", type: "text", required: false },
          { key: "lease_share_pct", type: "number", required: false },
          { key: "energy_source", type: "select", required: false, options: ["electricity", "mixed"] },
        ],
      },
    },
    440,
  ),
  withDefaults(
    {
      scope: "scope3",
      scope3Category: 14,
      key: "s3_cat14_franchises_spend",
      name: "Franchises · Spend",
      subGroup: "Franchises",
      method: "spend",
      unit: "EUR",
      defaultFactorKey: "ef_s3_cat14_franchises_kgco2e_per_eur",
      sdgs: [8, 12, 13],
      inputSchema: { fields: [{ key: "franchise_type", type: "text", required: false }] },
    },
    450,
  ),
  withDefaults(
    {
      scope: "scope3",
      scope3Category: 15,
      key: "s3_cat15_financed_emissions_tco2e",
      name: "Investments · Financed emissions",
      subGroup: "Investments",
      method: "direct_tco2e",
      unit: "tCO2e",
      requiresFactor: false,
      defaultFactorKey: null,
      sdgs: [8, 9, 13],
      inputSchema: { fields: [{ key: "asset_class", type: "text", required: false }] },
    },
    460,
  ),
];

const factor = (row) => ({
  library: "IPCC",
  country: null,
  reportingYear: null,
  scope: null,
  scope3Category: null,
  method: null,
  spendCategory: null,
  transportMode: null,
  refrigerantType: null,
  region: null,
  ...row,
});

export const GHG_FACTOR_LIBRARY_STARTER_ROWS = [
  factor({ key: "ef_s1_fuel_oil_kgco2e_per_liter", unit: "kgCO2e/liter", value: 3.12, sourceLabel: "DEFRA generic", sourceUrl: "https://www.gov.uk/government/collections/government-conversion-factors-for-company-reporting", notes: "Starter default" }),
  factor({ key: "ef_s1_lpg_kgco2e_per_liter", unit: "kgCO2e/liter", value: 1.51, sourceLabel: "DEFRA generic", sourceUrl: "https://www.gov.uk/government/collections/government-conversion-factors-for-company-reporting", notes: "Starter default" }),
  factor({ key: "ef_s1_coal_kgco2e_per_ton", unit: "kgCO2e/ton", value: 2410, sourceLabel: "IPCC default", sourceUrl: "https://www.ipcc-nggip.iges.or.jp/public/2006gl/vol2.html", notes: "Starter default" }),
  factor({ key: "ef_s1_biomass_kgco2e_per_ton", unit: "kgCO2e/ton", value: 0, sourceLabel: "IPCC guidance", sourceUrl: "https://www.ipcc-nggip.iges.or.jp/public/2006gl/vol2.html", notes: "Biogenic CO2 usually reported separately" }),
  factor({ key: "ef_s1_fleet_kgco2e_per_km", unit: "kgCO2e/km", value: 0.18, sourceLabel: "EEA starter", sourceUrl: "https://www.eea.europa.eu/", notes: "Starter default" }),
  factor({ key: "ef_s1_maritime_fuel_kgco2e_per_ton", unit: "kgCO2e/ton", value: 3114, sourceLabel: "IMO starter", sourceUrl: "https://www.imo.org/", notes: "Starter default" }),
  factor({ key: "ef_s1_aviation_fuel_kgco2e_per_ton", unit: "kgCO2e/ton", value: 3150, sourceLabel: "ICAO starter", sourceUrl: "https://www.icao.int/environmental-protection/", notes: "Starter default" }),
  factor({ key: "ef_s1_process_cement_clinker_kgco2e_per_ton", unit: "kgCO2e/ton", value: null, sourceLabel: "Industry specific", sourceUrl: "https://ghgprotocol.org/calculation-tools", notes: "Import sector factor" }),
  factor({ key: "ef_s1_process_lime_kgco2e_per_ton", unit: "kgCO2e/ton", value: null, sourceLabel: "Industry specific", sourceUrl: "https://ghgprotocol.org/calculation-tools", notes: "Import sector factor" }),
  factor({ key: "ef_s1_process_ammonia_kgco2e_per_ton", unit: "kgCO2e/ton", value: null, sourceLabel: "Industry specific", sourceUrl: "https://ghgprotocol.org/calculation-tools", notes: "Import sector factor" }),
  factor({ key: "ef_s2_steam_kgco2e_per_mwh", unit: "kgCO2e/MWh", value: null, sourceLabel: "National inventory", sourceUrl: "https://www.iea.org/data-and-statistics/data-tools/emissions-factors", notes: "Manual required" }),
  factor({ key: "ef_s2_heat_kgco2e_per_mwh", unit: "kgCO2e/MWh", value: null, sourceLabel: "National inventory", sourceUrl: "https://www.iea.org/data-and-statistics/data-tools/emissions-factors", notes: "Manual required" }),
  factor({ key: "ef_s2_cooling_kgco2e_per_mwh", unit: "kgCO2e/MWh", value: null, sourceLabel: "National inventory", sourceUrl: "https://www.iea.org/data-and-statistics/data-tools/emissions-factors", notes: "Manual required" }),
  factor({ key: "ef_s2_renewable_certificate_kgco2e_per_kwh", unit: "kgCO2e/kWh", value: 0, sourceLabel: "GHG Protocol", sourceUrl: "https://ghgprotocol.org/scope-2-guidance", notes: "Used when contractual instruments are valid" }),
  factor({ key: "ef_s3_cat1_spend_kgco2e_per_eur", unit: "kgCO2e/EUR", value: 0.35, scope: "scope3", scope3Category: 1, method: "spend", sourceLabel: "EEIO starter", sourceUrl: "https://www.epa.gov/statelocalenergy/portfolio-manager-ghg-emissions-technical-reference", notes: "Starter spend factor" }),
  factor({ key: "ef_s3_cat1_paper_kgco2e_per_ton", unit: "kgCO2e/ton", value: 1100, scope: "scope3", scope3Category: 1, method: "activity", sourceLabel: "DEFRA starter", sourceUrl: "https://www.gov.uk/government/collections/government-conversion-factors-for-company-reporting", notes: "Starter activity factor" }),
  factor({ key: "ef_s3_cat1_packaging_kgco2e_per_ton", unit: "kgCO2e/ton", value: 900, scope: "scope3", scope3Category: 1, method: "activity", sourceLabel: "DEFRA starter", sourceUrl: "https://www.gov.uk/government/collections/government-conversion-factors-for-company-reporting", notes: "Starter activity factor" }),
  factor({ key: "ef_s3_cat2_capex_kgco2e_per_eur", unit: "kgCO2e/EUR", value: 0.42, scope: "scope3", scope3Category: 2, method: "spend", sourceLabel: "EEIO starter", sourceUrl: "https://www.epa.gov/statelocalenergy/portfolio-manager-ghg-emissions-technical-reference", notes: "Starter spend factor" }),
  factor({ key: "ef_s3_cat3_wtt_fuel_kgco2e_per_liter", unit: "kgCO2e/liter", value: 0.65, scope: "scope3", scope3Category: 3, method: "activity", sourceLabel: "DEFRA upstream fuel", sourceUrl: "https://www.gov.uk/government/collections/government-conversion-factors-for-company-reporting", notes: "Starter upstream factor" }),
  factor({ key: "ef_s3_cat4_freight_kgco2e_per_ton_km", unit: "kgCO2e/ton_km", value: 0.08, scope: "scope3", scope3Category: 4, method: "activity", sourceLabel: "DEFRA freight", sourceUrl: "https://www.gov.uk/government/collections/government-conversion-factors-for-company-reporting", notes: "Starter freight factor" }),
  factor({ key: "ef_s3_cat5_waste_kgco2e_per_ton", unit: "kgCO2e/ton", value: 450, scope: "scope3", scope3Category: 5, method: "activity", sourceLabel: "DEFRA waste", sourceUrl: "https://www.gov.uk/government/collections/government-conversion-factors-for-company-reporting", notes: "Starter waste factor" }),
  factor({ key: "ef_s3_cat6_flight_kgco2e_per_pax_km", unit: "kgCO2e/pax_km", value: 0.146, scope: "scope3", scope3Category: 6, method: "activity", sourceLabel: "ICAO/DEFRA starter", sourceUrl: "https://www.icao.int/environmental-protection/", notes: "Starter flight factor" }),
  factor({ key: "ef_s3_cat6_rail_kgco2e_per_km", unit: "kgCO2e/km", value: 0.041, scope: "scope3", scope3Category: 6, method: "activity", sourceLabel: "EEA rail starter", sourceUrl: "https://www.eea.europa.eu/", notes: "Starter rail factor" }),
  factor({ key: "ef_s3_cat6_hotel_kgco2e_per_night", unit: "kgCO2e/night", value: 15.2, scope: "scope3", scope3Category: 6, method: "activity", sourceLabel: "Hotel benchmark starter", sourceUrl: "https://ghgprotocol.org/calculation-tools", notes: "Starter hotel factor" }),
  factor({ key: "ef_s3_cat7_commute_kgco2e_per_km", unit: "kgCO2e/km", value: 0.12, scope: "scope3", scope3Category: 7, method: "activity", sourceLabel: "Commuting starter", sourceUrl: "https://www.epa.gov/greenvehicles/greenhouse-gas-emissions-typical-passenger-vehicle", notes: "Starter commute factor" }),
  factor({ key: "ef_s3_cat8_leased_energy_kgco2e_per_kwh", unit: "kgCO2e/kWh", value: 0.32, scope: "scope3", scope3Category: 8, method: "activity", sourceLabel: "IEA starter proxy", sourceUrl: "https://www.iea.org/data-and-statistics/data-tools/emissions-factors", notes: "Starter screening proxy. Replace with lease-specific energy factor when available." }),
  factor({ key: "ef_s3_cat9_freight_kgco2e_per_ton_km", unit: "kgCO2e/ton_km", value: 0.08, scope: "scope3", scope3Category: 9, method: "activity", sourceLabel: "DEFRA freight", sourceUrl: "https://www.gov.uk/government/collections/government-conversion-factors-for-company-reporting", notes: "Starter freight factor" }),
  factor({ key: "ef_s3_cat10_processing_kgco2e_per_ton", unit: "kgCO2e/ton", value: 180, scope: "scope3", scope3Category: 10, method: "activity", sourceLabel: "GHG Protocol starter proxy", sourceUrl: "https://ghgprotocol.org/calculation-tools", notes: "Starter processing proxy. Replace with sector-specific process factor before assurance." }),
  factor({ key: "ef_s3_cat11_use_phase_kgco2e_per_kwh", unit: "kgCO2e/kWh", value: 0.32, scope: "scope3", scope3Category: 11, method: "activity", sourceLabel: "IEA use-phase proxy", sourceUrl: "https://www.iea.org/data-and-statistics/data-tools/emissions-factors", notes: "Starter electricity proxy. Validate operating profile and geography before sign-off." }),
  factor({ key: "ef_s3_cat12_eol_kgco2e_per_ton", unit: "kgCO2e/ton", value: 520, scope: "scope3", scope3Category: 12, method: "activity", sourceLabel: "Waste treatment starter", sourceUrl: "https://www.gov.uk/government/collections/government-conversion-factors-for-company-reporting", notes: "Starter factor" }),
  factor({ key: "ef_s3_cat13_leased_assets_kgco2e_per_kwh", unit: "kgCO2e/kWh", value: 0.32, scope: "scope3", scope3Category: 13, method: "activity", sourceLabel: "IEA starter proxy", sourceUrl: "https://www.iea.org/data-and-statistics/data-tools/emissions-factors", notes: "Starter screening proxy. Replace with lease-specific energy factor when available." }),
  factor({ key: "ef_s3_cat14_franchises_kgco2e_per_eur", unit: "kgCO2e/EUR", value: 0.3, scope: "scope3", scope3Category: 14, method: "spend", sourceLabel: "EEIO starter", sourceUrl: "https://www.epa.gov/statelocalenergy/portfolio-manager-ghg-emissions-technical-reference", notes: "Starter spend factor" }),
];

export const SOCIAL_METRIC_BASELINE = [
  {
    key: "s_hs_total_recordable_incidents",
    name: "Total recordable incidents",
    groupKey: "S",
    unit: "count",
    method: "manual",
    inputSchema: { fields: [] },
    formula: null,
    sdgs: [3, 8],
    evidenceRequired: true,
    isActive: true,
    sortOrder: 10,
  },
  {
    key: "s_hs_lost_time_incidents",
    name: "Lost-time incidents",
    groupKey: "S",
    unit: "count",
    method: "manual",
    inputSchema: { fields: [] },
    formula: null,
    sdgs: [3, 8],
    evidenceRequired: true,
    isActive: true,
    sortOrder: 20,
  },
  {
    key: "s_hs_hours_worked_total",
    name: "Hours worked total",
    groupKey: "S",
    unit: "hours",
    method: "computed",
    inputSchema: { fields: [] },
    formula: { source: "workforce_monthly", aggregation: "sum_hours_worked_total" },
    sdgs: [3, 8],
    evidenceRequired: false,
    isActive: true,
    sortOrder: 30,
  },
  {
    key: "s_hs_trir",
    name: "TRIR",
    groupKey: "S",
    unit: "rate",
    method: "computed",
    inputSchema: { fields: [] },
    formula: { expr: "(recordable_incidents*200000)/hours_worked_total" },
    sdgs: [3, 8],
    evidenceRequired: false,
    isActive: true,
    sortOrder: 40,
  },
  {
    key: "s_hs_ltifr",
    name: "LTIFR",
    groupKey: "S",
    unit: "rate",
    method: "computed",
    inputSchema: { fields: [] },
    formula: { expr: "(lost_time_incidents*1000000)/hours_worked_total" },
    sdgs: [3, 8],
    evidenceRequired: false,
    isActive: true,
    sortOrder: 50,
  },
  {
    key: "s_training_hours_total",
    name: "Training hours total",
    groupKey: "S",
    unit: "hours",
    method: "manual",
    inputSchema: { fields: [] },
    formula: null,
    sdgs: [4, 8],
    evidenceRequired: true,
    isActive: true,
    sortOrder: 60,
  },
  {
    key: "s_training_hours_per_employee",
    name: "Training hours per employee",
    groupKey: "S",
    unit: "hours/employee",
    method: "computed",
    inputSchema: { fields: [] },
    formula: { expr: "training_hours_total/avg_headcount" },
    sdgs: [4, 8],
    evidenceRequired: false,
    isActive: true,
    sortOrder: 70,
  },
  {
    key: "s_dei_gender_pay_gap_pct",
    name: "Gender pay gap (%)",
    groupKey: "S",
    unit: "%",
    method: "manual",
    inputSchema: { fields: [] },
    formula: null,
    sdgs: [5, 8, 10],
    evidenceRequired: true,
    isActive: true,
    sortOrder: 80,
  },
  {
    key: "s_dei_women_in_workforce_pct",
    name: "Women in workforce (%)",
    groupKey: "S",
    unit: "%",
    method: "computed",
    inputSchema: { fields: [] },
    formula: { source: "workforce_monthly", aggregation: "women_in_workforce_pct" },
    sdgs: [5, 8, 10],
    evidenceRequired: false,
    isActive: true,
    sortOrder: 90,
  },
  {
    key: "s_dei_women_in_management_pct",
    name: "Women in management (%)",
    groupKey: "S",
    unit: "%",
    method: "computed",
    inputSchema: { fields: [] },
    formula: { source: "management_headcount_yearly", aggregation: "women_in_management_pct" },
    sdgs: [5, 8, 10],
    evidenceRequired: false,
    isActive: true,
    sortOrder: 100,
  },
  {
    key: "s_turnover_pct",
    name: "Turnover (%)",
    groupKey: "S",
    unit: "%",
    method: "computed",
    inputSchema: { fields: [] },
    formula: { source: "workforce_leavers_monthly", aggregation: "turnover_pct" },
    sdgs: [8],
    evidenceRequired: false,
    isActive: true,
    sortOrder: 110,
  },
  {
    key: "s_absenteeism_days",
    name: "Absenteeism days",
    groupKey: "S",
    unit: "days",
    method: "manual",
    inputSchema: { fields: [] },
    formula: null,
    sdgs: [3, 8],
    evidenceRequired: true,
    isActive: true,
    sortOrder: 120,
  },
  {
    key: "s_absenteeism_rate",
    name: "Absenteeism rate (%)",
    groupKey: "S",
    unit: "%",
    method: "computed",
    inputSchema: { fields: [] },
    formula: { expr: "absenteeism_days/(avg_headcount*working_days)" },
    sdgs: [3, 8],
    evidenceRequired: false,
    isActive: true,
    sortOrder: 130,
  },
  {
    key: "s_union_coverage_pct",
    name: "Collective bargaining coverage (%)",
    groupKey: "S",
    unit: "%",
    method: "manual",
    inputSchema: { fields: [] },
    formula: null,
    sdgs: [8, 10],
    evidenceRequired: true,
    isActive: true,
    sortOrder: 140,
  },
  {
    key: "s_supplier_screened_count",
    name: "Suppliers screened (social criteria)",
    groupKey: "S",
    unit: "count",
    method: "manual",
    inputSchema: { fields: [] },
    formula: null,
    sdgs: [8, 12],
    evidenceRequired: true,
    isActive: true,
    sortOrder: 150,
  },
];
